### ISSUE TITLE
 LookupError:  unknown encoding: auto 

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#17]
After adding a teacher and clicking "Save&Check" I get this error:

`POST /api/lm/users/teachers?encoding=auto`

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lm_users/views.py", line 96, in handle_api_teachers
    ).writerows(data)
  File "/usr/lib/python2.7/csv.py", line 158, in writerows
    return self.writer.writerows(rows)
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 90, in writerows
    self.writerow(row)
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 86, in writerow
    _stringify_list(row, self.encoding, self.encoding_errors))
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 48, in _stringify_list
    return [_stringify(s, encoding, errors) for s in iter(l)]
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 38, in _stringify
    return s.encode(encoding, errors)
LookupError: unknown encoding: auto
```

**Comment by PLanB2008** [comment]
Closed with https://github.com/linuxmuster/sophomorix4/issues/45
