### ISSUE TITLE
Server error on login in 7.2.20

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#264]
Hi @kiarn 

I just upgraded to `7.2.20` and now get a server error on login of a normal student:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aj/api/endpoint.py", line 77, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_core/views/api.py", line 141, in handle_api_auth
    auth_info = auth.check_password(username, password)
  File "/usr/local/lib/python3.10/dist-packages/aj/auth.py", line 192, in check_password
    return self.get_provider().authenticate(username, password)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_auth/api.py", line 136, in authenticate
    userAttrs = self.get_ldap_user(username)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_auth/api.py", line 55, in get_ldap_user
    return self.lr.get(f'/user/{username}', school_oriented=False)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_common/ldap/requests.py", line 32, in get
    return method(**data, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_common/ldap/requests.py", line 53, in get_user
    return self.lc.get_single(LMNUser, ldap_filter, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_common/ldap/connector.py", line 41, in get_single
    return asdict(objectclass(**data))
  File "<string>", line 55, in __init__
  File "/usr/lib/linuxmuster-webui/plugins/lmn_common/ldap/models/lmnuser.py", line 119, in __post_init__
    self.schoolclasses = self.extract_schoolclasses(self.memberOf)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_common/ldap/models/lmnuser.py", line 91, in extract_schoolclasses
    schoolclasses = sorted(schoolclasses, key=lambda s: int(re.findall(r'\d+', s)[0]))
  File "/usr/lib/linuxmuster-webui/plugins/lmn_common/ldap/models/lmnuser.py", line 91, in <lambda>
    schoolclasses = sorted(schoolclasses, key=lambda s: int(re.findall(r'\d+', s)[0]))
IndexError: list index out of range
```

Not sure, what causes this. Login works for global admins.

Best regards,
Dorian

**Comment by kiarn** [comment]
Hi Dorian,

Does your student belong to a schoolclass ? If yes, what is the name of the schoolclass ?

Arnaud

**Comment by dorianim** [comment]
Yep:
![image](https://github.com/linuxmuster/linuxmuster-webui7/assets/30153207/287d3bc8-18dd-426d-93e0-af71776d8378)

**Comment by kiarn** [comment]
Ok, the problem is that I'm trying to sort the schoolclasses by integer, and your schoolclass is only letters.
I will fix it.
