### ISSUE TITLE
Set Custom Password does not work

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#32]
I can't set a custom password for a teacher:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_users/views.py", line 303, in handle_api_users_password
    return lmn_getSophomorixValue(sophomorixCommand, 'COMMENT_EN')
  File "/usr/lib/linuxmuster-webui/plugins/lm_common/api.py", line 107, in lmn_getSophomorixValue
    jsonS = subprocess.Popen(sophomorixCommand, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=False).stdout.read()
  File "/usr/local/lib/python2.7/dist-packages/aj/compat.py", line 25, in Popen
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 585, in __init__
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 554, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 1312, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

**Comment by netzint** [comment]
should be fixed in the latest release, please test again
