### ISSUE TITLE
 [Errno 2] No such file or directory: '/etc/cups/access.conf' 

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#4]
While trying to access the printers section I get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lm_printers/views.py", line 24, in handle_api_printers
    for line in open(access_path):
IOError: [Errno 2] No such file or directory: '/etc/cups/access.conf'
```

**Comment by PLanB2008** [comment]
List entry removed
