### ISSUE TITLE
Quota:  list index out of range 

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#5]
There is an index error, when you try to access the Quota section:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lm_quotas/views.py", line 78, in handle_api_class_quotas
    for line in lines
IndexError: list index out of range
```

**Comment by netzint** [comment]
This feature is not implemented at the moment. This module is only ported from the linuxmuster 6.2 webui.
