### ISSUE TITLE
 [Errno 2] No such file or directory: '/home/share/school' 

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#6]
When I try to access Settings under Settings & Defaults I get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lm_settings/views.py", line 116, in handle_api_school_share
    print os.stat(path).st_mode
OSError: [Errno 2] No such file or directory: '/home/share/school'
```

**Comment by netzint** [comment]
This feature is not implemented at the moment. This module is only ported from the linuxmuster 6.2 webui.

**Comment by PLanB2008** [comment]
List entry removed
