### ISSUE TITLE
 Command 'sophomorix-print -a' returned non-zero exit status 88 

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#8]
When I try to print all passwords:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lm_users/views.py", line 310, in handle_api_users_print
    subprocess.check_call(cmd, shell=True)
  File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 260, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'sophomorix-print -a' returned non-zero exit status 88

```

**Comment by jeffbeck** [comment]
sophomorix-print -a
"-a" is not a valid option for sophomorix-print

**Comment by netzint** [comment]
This feature is not implemented at the moment. This module is only ported from the linuxmuster 6.2 webui.

**Comment by PLanB2008** [comment]
Print feature got implemented a while ago. Please test!
