### ISSUE TITLE
Server Error when logging in (with global-admin)

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#96]
When I want to login with global-admin I get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_users/views.py", line 146, in handle_api_sophomorix_students
    studentsCheck = lmn_getSophomorixValue(sophomorixCommand, 'LISTS/USER')
  File "/usr/lib/linuxmuster-webui/plugins/lmn_common/api.py", line 192, in lmn_getSophomorixValue
    'Error Message: ' + str(e) + '\n Dictionary we looked for information:\n  ' + str(jsonDict))
Exception: getSophomorix Value error. Either sophomorix field does not exist or ajenti binduser does not have sufficient permissions:
Error Message: 'LISTS/USER'
 Dictionary we looked for information:
  {}
```
Its a freshly provisioned system with no teacher / student users.

**Comment by kiarn** [comment]
Hello @zefanja,

What's the output of `sophomorix-admin -i` ?

**Comment by zefanja** [comment]
```
$:~# sophomorix-admin -i
Command line::
Option verbose is a modifier option
Hmmh. do not know what to do with option info
Option json is a modifier option
* forcing info mode
Option combinations successfully checked
OK: SophomorixSchemaVersion 1 matches required Version 1
#### Reading /usr/share/sophomorix/devel/sophomorix.ini                   ####
Distro-check: Ubuntu 18.04 is OK
#### Reading /etc/samba/smb.conf                                          ####
#### Reading /usr/lib/linuxmuster-webui/etc/default-ui-permissions.ini    ####
#### Parsing: net conf list                                               ####
#### Asking domain passwordsettings from samba                            ####
#### Reading /usr/share/sophomorix/devel/master/sophomorix.conf.master    ####
#### Reading /etc/linuxmuster/sophomorix/sophomorix.conf                  ####
#### OK: default-school share exists                                      ####
#### OK: /etc/linuxmuster/sophomorix/default-school/school.conf           ####
#### Reading /usr/share/sophomorix/devel/master/school.conf.master        ####
#### Reading /etc/linuxmuster/sophomorix/default-school/school.conf       ####
#### 2 administrators in school global:                                   ####
+----------------------+-+-------------------------+------+--------------------------------+
| Administrator        |P| displayName             | Role | Comment                        |
+----------------------+-+-------------------------+------+--------------------------------+
| global-admin         |F| Global Admin            | gadm | created by linuxmuster-setup   |
| global-binduser      |T| Global Binduser         | gbin | created by linuxmuster-setup   |
+----------------------+-+-------------------------+------+--------------------------------+
P: Password file exists(T) or not(F)   gadm: globaladministrator   gbin: globalbinduser

#### 0 administrators in school default-school:                           ####
```

**Comment by kiarn** [comment]
Oh, wait, I misunderstood the problem : the user global-admin can log in, but you get an error with the url http(s)://10.0.0.1:8000/view/lm/users/students-list because there's no students yet.
So, I think we can simply show an info message when the dict is empty.

**Comment by kiarn** [comment]
I think it's solved with https://github.com/linuxmuster/linuxmuster-webui7/commit/4ac566fd8f339c9ad10a37e6cbe09e0b087bc1b5
